### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by charlesoruko** [EternallLight/cordova-plugin-openwith-ios#21]
Failed to install 'com.web-mystery.cordova.openwith-ios': CordovaError: Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/developerskenya/desktop/text/sharetest/plugins/com.web-mystery.cordova.openwith-ios/hooks/npmInstall.js:24:33)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by charlesoruko** [comment]
Resolved this issue by using a different plugin https://github.com/ygyg70/cordova-plugin-openwith ,
works with android 9.
