### ISSUE TITLE
Can't install/compile with latest version of cordova

### ISSUE THREAD

**Issue by ygyg70** [EternallLight/cordova-plugin-openwith-ios#7]
Cordova-cli version: 8.0.0
Cordova-ios version: 4.5.5
Add plugin error:
iOS project created with cordova-ios@4.5.5
Installing "com.web-mystery.cordova.openwith-ios" for ios
Installing "com.web-mystery.cordova.openwith-ios" dependencies
Copying "com.web-mystery.cordova.openwith-ios/ShareExtension" to ios...
Failed to install 'com.web-mystery.cordova.openwith-ios': Error: Missing key while parsing <dict/>.
    at invariant (/Users/{path}/platforms/ios/cordova/node_modules/plist/lib/parse.js:53:11)
    at parsePlistXML (/Users/{path}/platforms/ios/cordova/node_modules/plist/lib/parse.js:115:9)
    at parsePlistXML (/Users/{path}/platforms/ios/cordova/node_modules/plist/lib/parse.js:143:15)
    at parsePlistXML (/Users/{path}/platforms/ios/cordova/node_modules/plist/lib/parse.js:101:23)
    at Object.parse (/Users/{path}/platforms/ios/cordova/node_modules/plist/lib/parse.js:71:15)
    at Object.graftPLIST (/Users/{path}/platforms/ios/cordova/node_modules/cordova-common/src/util/plist-helpers.js:28:21)
    at ConfigFile_graft_child [as graft_child] (/Users/{path}/platforms/ios/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:126:40)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (/Users/{path}/platforms/ios/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:81:34)
    at munge_helper (/Users/{path}/platforms/ios/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:238:14)
    at PlatformMunger.add_plugin_changes (/Users/{path}/platforms/ios/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:159:12)

Any help is extremely appreciated

**Comment by Konkrad** [comment]
I got the same problem. You already found a solution?

**Comment by ygyg70** [comment]
No Solution yet

**Comment by Konkrad** [comment]
Thank you for showing me that the problem was the updated version of cordova-ios. I now downgraded it in the meantime with ```cordova platform add ios@4.5.4```

**Comment by ygyg70** [comment]
My problem with ios 4.5.4 was that the build got broken - looks like a conflict between cordova-plugin-push and the share extension.
I was hoping that getting everything on latest versions would resolve that :(

**Comment by olaferlandsen** [comment]
> Thank you for showing me that the problem was the updated version of cordova-ios. I now downgraded it in the meantime with `cordova platform add ios@4.5.4`

thats work for me!
